name: Build
on:
    workflow_dispatch:
    push:
        paths:
            - "*.py"
            - "requirements.txt"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
                  cache: "pip" # caching pip dependencies
            - run: pip install -r requirements.txt
            - run: python generate.py
            - name: Upload Artifacts
              uses: actions/upload-artifact@v3
              with:
                  path: dist/*.json
